FernetMenta/xbmc

Kodi.xcodeproj/project.pbxproj

[osx/ios/atv2] - sync xcode project

---

xbmc/windowing/X11/GLContextEGL.cpp

EGL: Ask for alpha, red, blue, green and depth

---

xbmc/cores/dvdplayer/DVDCodecs/Video/VAAPI.cpp

VAAPI: Fix compiler warnings (squash me)

---

xbmc/cores/VideoRenderers/HwDecRender/RendererVDPAU.cpp

[vdpau] fix build breakage after 48ba764af

---

Kodi.xcodeproj/project.pbxproj
project/VS2010Express/XBMC.vcxproj
project/VS2010Express/XBMC.vcxproj.filters
xbmc/cores/FFmpeg.h
xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.h
xbmc/music/tags/Makefile
xbmc/music/tags/MusicInfoTagLoaderFFmpeg.cpp
xbmc/music/tags/MusicInfoTagLoaderFFmpeg.h
xbmc/music/tags/MusicInfoTagLoaderFactory.cpp

This adds a ffmpeg based music tagloader and use it for a few formats not supported by taglib.

Add ffmpeg tagloader

---

xbmc/cores/VideoPlayer/VideoRenderers/BaseRenderer.cpp

This reverts commit 382d4090b7dfdaa4db22f84dc530fb7d8dad9436.
Let's discuss this again on the scratchboard.

Revert "AdjustRefreshrate: Allow switching to higher resolution"

---

xbmc/addons/Visualisation.cpp
xbmc/cores/AudioEngine/AEFactory.cpp
xbmc/cores/AudioEngine/AEFactory.h
xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp
xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.h
xbmc/cores/AudioEngine/Interfaces/AE.h

changed: allow multiple callbacks in AE

---

xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp
xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp
xbmc/cores/VideoPlayer/VideoRenderers/WinRenderer.cpp
xbmc/settings/AdvancedSettings.cpp
xbmc/settings/AdvancedSettings.h

Not sure what to do with GLES.

Advancedsettings: Remove blackbarcolour and set it automatically

---

xbmc/cores/AudioEngine/Utils/AEBitstreamPacker.h

Windows ... windows ... windows :-)

AE: Fix include (some non broken FS can do upper / lower case)

---

xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp
xbmc/cores/paplayer/AudioDecoder.h

EAC3 is currently not testable - seems the settings are confused somehow with the new format. At least it compiles again. I will pick it up again and retest EAC3
AC3 was working with the transcoder.

AE: minors and WIP

---

xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp
xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.cpp
xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp
xbmc/cores/AudioEngine/Sinks/AESinkOSS.cpp
xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp
xbmc/cores/AudioEngine/Sinks/AESinkPi.cpp
xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.cpp
xbmc/cores/AudioEngine/Sinks/osx/AEDeviceEnumerationOSX.cpp
xbmc/cores/AudioEngine/Utils/AEDeviceInfo.h

Needs more clue in ActiveAESink

AE: Extend DeviceInfo

---

xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp
xbmc/cores/AudioEngine/Sinks/AESinkOSS.cpp
xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp

AE: Adjustments after CAEStreamInfo::DataType changes

---

xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp
xbmc/cores/AudioEngine/Sinks/AESinkALSA.h
xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp

PULSE needs to announce AE_FMT_RAW or it is not called at all.
There was a missing break, which would cause DTSHD, and all other DTS being shipped as 192 khz

AE: Some minors

---

project/VS2010Express/XBMC.vcxproj
project/VS2010Express/XBMC.vcxproj.filters
xbmc/cores/VideoPlayer/VideoRenderers/WinRenderer.cpp
xbmc/rendering/dx/RenderSystemDX.cpp
xbmc/rendering/dx/RenderSystemDX.h
xbmc/win32/WIN32Util.cpp
xbmc/win32/Win32DelayedDllLoad.cpp
xbmc/windowing/windows/WinSystemWin32.cpp
xbmc/windowing/windows/WinSystemWin32.h
xbmc/windowing/windows/WinSystemWin32DX.cpp
xbmc/windowing/windows/WinSystemWin32DX.h

@FernetMenta please take a look.

[VideoPlayer] win32 adjustments.

---

xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp

Looks a bit ugly, but should do the job.

ActiveAESink: Check StreamInfo if AE_FMT_RAW

---

xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp
xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp
xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp

1) Sorry typo in my older commit :-)
2) We need to setup the StreamInfo struct correctly when we use it for settings probing

AE-WIP: Small fixes

---

addons/library.kodi.audioengine/libKODI_audioengine.h
xbmc/ApplicationPlayer.cpp
xbmc/ApplicationPlayer.h
xbmc/GUIInfoManager.cpp
xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.cpp
xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.h
xbmc/cores/IPlayer.h
xbmc/cores/VideoPlayer/DVDMessage.h
xbmc/cores/VideoPlayer/VideoPlayer.cpp
xbmc/cores/VideoPlayer/VideoPlayer.h
xbmc/settings/VideoSettings.h
xbmc/video/dialogs/GUIDialogAudioSubtitleSettings.cpp
xbmc/video/dialogs/GUIDialogAudioSubtitleSettings.h
xbmc/video/windows/GUIWindowFullScreen.cpp

Hacked on the fly, but it seems to work (only tested one sample).

[RFC] Multi video streams

---

xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.cpp
xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp
xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.cpp

Needs runtime testing on windows

AESink: Port sinks to new stream types

---

xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp

This fixes the one outstanding bracket. Please let jenkins fully run - blind fixing stuff sucks.

AESinkDirectSound: Squash me

---

xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.cpp
xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.h

We need a windows dev here ... this AE_FMT_LPCM was never used by us anyways ...

AESinkWASAPI: More clean up

---

project/cmake/CMakeLists.txt
project/cmake/treedata/common/music.txt
project/cmake/treedata/common/subdirs.txt
project/cmake/treedata/linux/subdirs.txt
xbmc/CMakeLists.txt
xbmc/cores/CMakeLists.txt
xbmc/guilib/CMakeLists.txt
xbmc/main/posix/CMakeLists.txt
xbmc/platform/CMakeLists.txt
xbmc/platform/posix/CMakeLists.txt
xbmc/pvr/CMakeLists.txt
xbmc/pvr/windows/CMakeLists.txt

Hi @FernetMenta, I found the CMake based build system in your repo and wanted to play around a bit with it. This commit makes it compile again. Do you have a list of what is working and what needs to be done? Guess I could help out a bit with it.
Cheers, Christian

[cmake] Fix compilation

---

xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecVideoToolBox.cpp

I think this is what you wanted? :)

[VTB] - Check for supported codecs inside vtb decoder

---

project/cmake/CMakeLists.txt
project/cmake/scripts/windows/archsetup.cmake
project/cmake/scripts/windows/macros.cmake

Compiles and links on Windows (nmake-generator). Doesn't start yet though.

[cmake] More work on Windows support

---

.gitignore
project/cmake/modules/FindJsonSchemaBuilder.cmake
project/cmake/scripts/darwin/archsetup.cmake
project/cmake/scripts/darwin/macros.cmake
tools/EventClients/Clients/OSXRemote/CMakeLists.txt
tools/depends/native/JsonSchemaBuilder/CMakeLists.txt
xbmc/music/windows/CMakeLists.txt
xbmc/utils/test/CMakeLists.txt
xbmc/video/windows/CMakeLists.txt

Builds now also with xcodebuild:
```
mkdir kodi-build && cd kodi-build
cmake -DCMAKE_TOOLCHAIN_FILE=../kodi/tools/depends/target/Toolchain.cmake -G "Xcode" ../kodi/project/cmake/
cmake --build . --config "Debug" -- -verbose -jobs $(sysctl -n hw.ncpu)
KODI_HOME=$(pwd) ./Debug/kodi.bin
```
@memphiz fyi :)

[cmake] More work on OSX

---

xbmc/addons/include/xbmc_inputstream_types.h

I'll start with the addon using this step of interface implementation

Added supported URLs filter

---

xbmc/addons/include/kodi_inputstream_dll.h
xbmc/addons/include/kodi_inputstream_types.h

Pls. let me know if the structs are enough/ OK.
If so I'll start implementing them in the test addon.

INPUTSTREAM struct for OpenStream, GetStreamInfo() implemented

---

project/VS2010Express/XBMC.vcxproj
project/VS2010Express/XBMC.vcxproj.filters

fixed linking errors (unresolved dependencies) in VS-Studio

InputStream -> vcxproj

---

xbmc/addons/AddonCallbacks.cpp

AddonCallbacks: properly initialize ptr (squash me)

---

xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp
xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp
xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.h
xbmc/cores/VideoPlayer/Process/Makefile
xbmc/cores/VideoPlayer/Process/overrides/rbp/ProcessInfoPi.cpp
xbmc/cores/VideoPlayer/Process/overrides/rbp/ProcessInfoPi.h
xbmc/cores/VideoPlayer/VideoPlayer.cpp
xbmc/cores/omxplayer/OMXPlayerAudio.cpp
xbmc/cores/omxplayer/OMXPlayerAudio.h
xbmc/cores/omxplayer/OMXPlayerVideo.cpp
xbmc/cores/omxplayer/OMXPlayerVideo.h

Just for comments.
I've hand edited the Makefile which needs handling properly.
I'm not sure if ProcessInfoPi is quite what you had in mind.
It doesn't actually work due to the filters/EINTERLACEMETHOD mixup.

processinfo: Add mmal support

---

xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp
xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp
xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp
xbmc/cores/omxplayer/OMXAudioCodecOMX.cpp
xbmc/cores/omxplayer/OMXAudioCodecOMX.h
xbmc/cores/omxplayer/OMXPlayerAudio.cpp
xbmc/cores/omxplayer/OMXPlayerVideo.cpp
xbmc/cores/omxplayer/OMXVideo.cpp
xbmc/cores/omxplayer/OMXVideo.h

The first commit is to fix some incorrect/uninitialised values I found when testing.
The second adds support for omxplayer/mmal.

VideoPlayer: expose stream player info to GUI 

---

xbmc/GUIInfoManager.cpp
xbmc/cores/DataCacheCore.cpp
xbmc/cores/DataCacheCore.h
xbmc/cores/VideoPlayer/Process/ProcessInfo.cpp
xbmc/cores/VideoPlayer/Process/ProcessInfo.h

- Use std::find instead of for loop
- Fix Sampe vs Sample

Some minor fixes

---

xbmc/test/TestBasicEnvironment.cpp

Fix tests (squash me)

---

xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp
xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.h

MMAL: Update to new dropping scheme

---

xbmc/cores/VideoPlayer/CMakeLists.txt

Minor bikeshedding compensation :-)

Squash me (cmake sort alphabetical)

---

xbmc/linux/OMXClock.cpp
xbmc/windowing/X11/CMakeLists.txt
xbmc/windowing/egl/VideoSyncPi.cpp
xbmc/windowing/egl/VideoSyncPi.h

There may be a better place for the cmake hack, but this makes it build.

Vsync fixes for pi

---

xbmc/cores/RetroPlayer/RetroPlayerAudio.cpp

Is this the change you were talking about in https://github.com/xbmc/xbmc/pull/11765?

Fix RetroPlayer audio after AE updates

---

xbmc/test/TestBasicEnvironment.cpp

not 100% sure if this is the correct fix, but it works for me
100% tests passed, 0 tests failed out of 495

[AE] fix unit tests

---

xbmc/settings/dialogs/CMakeLists.txt
xbmc/settings/dialogs/GUIDialogAudioDSPManager.cpp

@FernetMenta see title. Please trigger a jenkins build, as I only had access to Windows.

Fix AudioDSP Manager Dialog Build Issues

---

xbmc/input/linux/LinuxInputDevices.cpp
xbmc/input/touch/generic/GenericTouchActionHandler.cpp
xbmc/platform/android/activity/AndroidKey.cpp
xbmc/platform/android/activity/AndroidMouse.cpp
xbmc/windowing/X11/WinEventsX11.cpp
xbmc/windowing/mir/WinEventsMir.cpp

Fix fallout

---

xbmc/windowing/windows/WinEventsWin32.cpp

Fix XBMC_event fallout in WinEventsWin32
