- xbmc/cores/dvdplayer/DVDCodecs/Video/VAAPI.cpp
In a perfect world - we could use the VPP configs directly ...
> VPP: Use color standards (fast path - other is broken)

- xbmc/cores/dvdplayer/DVDCodecs/Video/VAAPI.cpp
- xbmc/linux/PlatformDefs.h
fourcc has changed after @chadversary prd those to upstream, see: https://github.com/chadversary/mesa/commit/12dcbfff06bd3b4a1e51c25ede5351bad95ab88e
Second hunk: EGL currently does not build on i386 as it seems the system_gl.h is included too late - this is a lazy workaround, input is needed.
> Minor fixes

- xbmc/cores/VideoPlayer/VideoRenderers/BaseRenderer.cpp
This allows users to run their GUI in e.g. 1080p50 and we will automatically switch to a higher resolution when there is a good match for content, e.g. 4k@24p.
> AdjustRefreshrate: Allow switching to a higher resolution with best match

- xbmc/windowing/X11/WinSystemX11.cpp
Should make us run on Gnome3 now, too. Unity uses something completely different no via the XAtoms, so I did not find a solution there.
> Disable additional compositors and guard them

- xbmc/cores/VideoPlayer/VideoRenderers/BaseRenderer.cpp
Please squash this one to: db9d3e4e2a970ad60aa5c50f6ff01fb4db824374 
The old code would try 1920x1080 for a 1080i50 source first and afterwards 1280x720@50p would not be settable anymore cause of the comparison with curr which already would be 1920x1080 then.
> AdjustRefreshrate: Compare with original resolution not with a temporary

- Kodi.xcodeproj/project.pbxproj
- xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererVTB.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererVTB.h
- xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.h
- xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/GLSLOutput.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/YUV2RGBShader.cpp
Here is the start of the gles video renderer refactor. This adds RendererVTB and makes gles software rendering work.
All other hw dec renderers need to be moved into their own implementations by the code maintainers of those (though its pretty straight forward - basically derive a class from LinuxRendererGLES - search for the hw dec define in it and move that stuff into the overridden methods in the impl.)
Fernet i think i got the intention now ;)
> Hwdecrenderer gles vtb

- tools/depends/target/Makefile
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.h
The included change add the support for build with ./tools/buildsteps/* and ./tools/depends/target/* used from jenkins (I think jenkins itself still have not this libs).
Is tested here with Ubuntu vivid 64bit and was possible to build, run and play with standard package from http://packages.ubuntu.com/vivid/libegl1-mesa-dev. Without them from https://launchpad.net/~wsnipex/+archive/ubuntu/mesa/+packages :D .
What need to check on end is libxcb-dri2. Not sure that on end two independent libs are needed, I think no, currently yes. <b>EDIT:</b> Seen also on "wily" required.
The other to check is libGLEW on Mac OS X, think is maybe not required anymore.
Further has I added the temporary TODO strings in the Makefile, hope is OK. Still in development ;)
For the Makefile I has separated the …
> Add X11 EGL depends build support and DVDVideoCodec.* cleanup

- addons/library.kodi.guilib/libKODI_guilib.h
- lib/addons/library.kodi.guilib/libKODI_guilib.cpp
- xbmc/Application.cpp
- xbmc/addons/AddonCallbacks.h
- xbmc/addons/AddonCallbacksGUI.cpp
- xbmc/addons/AddonCallbacksGUI.h
- xbmc/addons/Visualisation.cpp
- xbmc/addons/Visualisation.h
- xbmc/addons/include/xbmc_vis_dll.h
- xbmc/addons/include/xbmc_vis_types.h
- xbmc/cores/AudioEngine/AEFactory.cpp
- xbmc/cores/AudioEngine/AEFactory.h
- xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp
- xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.h
- xbmc/cores/AudioEngine/Interfaces/AE.h
- xbmc/guilib/GUIControlFactory.cpp
- xbmc/guilib/GUIRenderingControl.cpp
- xbmc/guilib/GUIVisualisationControl.cpp
- xbmc/guilib/GUIVisualisationControl.h
- xbmc/guilib/IRenderingCallback.h
- introduce a manager for instances of visualisation addons
- use this to detach a visualisation's lifecycle from a visualisation
gui control's life cycle
- introduce multiple slots for visualization - allowing multiple
displayed at the same time. this is exposed to skinners through the
subtags 'slot' (just some number) and 'id' (the add-on id for the
visualization).    
-  add-ons needs to be updated, as the API changes. we have to change the Start()
method to pass screen info since this is now called once per gui control
instance. Likewise Stop() is called when the gui control is killed.
-   Create() is called at the beginning of the life cycle, and Create()
at the end. These are called exactly once.
Right now the only add-on I have updated is …
> Improve visualization API

- xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererIMX.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp
This PR fixes compilation and rendering for iMX6 target following PR https://github.com/FernetMenta/xbmc/pull/285 
imx hw buffers are ref counted and I have carefully checked that this PR restores proper behavior by monitoring this lock counter.
Now this seems fine but obviously wider testing would be welcome...
As a side note for imx6 users/packagers, in my env, I also had to revert commit https://github.com/wolfgar/xbmc/commit/bbbb46947b5306278b1f4375908f5a5395d6d073 otherwise I am quickly hit by the following glibc assertion error about lock :
```
pthread_mutex_lock.c:348: __pthread_mutex_lock_full: Assertion `(-(e)) != 35 || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)' failed
```
Obviously it is not kodi code which is bad here but there is likely an …
> [iMX6] fix compilation and rendering

- project/cmake/modules/FindCpluff.cmake
- project/cmake/modules/FindLibDvd.cmake
- project/cmake/treedata/linux/subdirs.txt
- project/cmake/treedata/rbpi/subdirs.txt
- xbmc/cores/VideoPlayer/VideoRenderers/CMakeLists.txt
- xbmc/cores/VideoPlayer/VideoRenderers/yuv2rgb.neon.S
- xbmc/input/CMakeLists.txt
- xbmc/input/touch/CMakeLists.txt
- xbmc/input/touch/generic/CMakeLists.txt
this syncs cmake and should hopefully fix the issues @popcornmix has with building on rpi in https://github.com/FernetMenta/xbmc/pull/298
Since building OMXplayer is broken after the recent audio sync changes, I've added a hackjob to make it _build_ again. I've almost certainly broken something, but videoplayer/omxplayer internals are above my paygrade ;) Maybe it can serve as a starting point for popcornmix or someone else to properly sync up with the recent changes.
> cmake updates

- xbmc/rendering/gles/RenderSystemGLES.h
- xbmc/system.h
- xbmc/windowing/WindowingFactory.h
- xbmc/windowing/X11/GLContext.h
- xbmc/windowing/X11/GLContextEGL.cpp
- xbmc/windowing/X11/GLContextEGL.h
- xbmc/windowing/X11/GLContextGLX.cpp
- xbmc/windowing/X11/GLContextGLX.h
- xbmc/windowing/X11/Makefile
- xbmc/windowing/X11/WinSystemX11GLContext.cpp
- xbmc/windowing/X11/WinSystemX11GLESContext.cpp
- xbmc/windowing/X11/WinSystemX11GLESContext.h
With this patch the code is able to compile and run properly on an EGL/GLES2 target over X11.
The changes from https://github.com/xbmc/xbmc/pull/8234 have been merged, too.
I tried to keep modifications to the absolute necessary ones to make it work, therefore the refactoring is still in progress.
Currently the classes *CWinSystemX11GLContextEGL* and *CWinSystemX11GLContext* have exactly the same interface, therefore in a future version can be easily derived from a common class.
> Egl refactoring

- xbmc/cores/FFmpeg.h
- xbmc/cores/VideoPlayer/DVDCodecs/DVDCodecUtils.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.h
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecVDA.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.h
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.h
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VDA.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VDA.h
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VDPAU.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Video/VDPAU.h
- xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp
- xbmc/cores/VideoPlayer/DVDFileInfo.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp
- xbmc/cores/VideoPlayer/VideoRenderers/WinRenderer.cpp
- xbmc/pictures/Picture.cpp
- xbmc/video/FFmpegVideoDecoder.cpp
The deprecated PixelFormat and PIX_FMT_* names have been removed in
ffmpeg master.
NB: None of the non-Linux changes have been tested.
> ffmpeg: Update AVPixelFormat and AV_PIX_FMT_* to compile with master

- xbmc/addons/include/kodi_audioengine_types.h
- xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
- xbmc/cores/AudioEngine/Sinks/AESinkDARWINIOS.cpp
- xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp
- xbmc/cores/AudioEngine/Sinks/AESinkPi.cpp
- xbmc/cores/AudioEngine/Sinks/AESinkWASAPI.cpp
- xbmc/cores/AudioEngine/Sinks/test/TestAESinkDARWINOSX.cpp
Remove attribute from the sink's implementation after removal
> AESink: Remove m_frameSamples from sink implementations

- xbmc/cores/AudioEngine/Utils/AEDeviceInfo.cpp
- xbmc/cores/AudioEngine/Utils/AEUtil.cpp
- xbmc/cores/AudioEngine/Utils/AEUtil.h
Looks like:
```
17:31:48 T:139787532458112  NOTICE:     Device 2
17:31:48 T:139787532458112  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2
17:31:48 T:139787532458112  NOTICE:         m_displayName     : Internes Audio Digital Stereo (HDMI 3)
17:31:48 T:139787532458112  NOTICE:         m_displayNameExtra: HDMI / DisplayPort 3 (PULSEAUDIO)
17:31:48 T:139787532458112  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
17:31:48 T:139787532458112  NOTICE:         m_channels        : FL,FR
17:31:48 T:139787532458112  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
17:31:48 T:139787532458112  NOTICE:         m_dataFormats     : …
```
> AEUtils: Add Streamtypes to Enumeration output

- xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp
- xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.cpp
- xbmc/cores/paplayer/PAPlayer.cpp
We need to take great care ... in passthrough case the m_StreamInfo should have _all_ the data we need - now let's test EAC3.
> DVDAudioCodecPassthrough: Set samplerate when creating StreamInfo

- xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEStream.cpp
Follow up of this discussion: https://github.com/FernetMenta/xbmc/commit/adfa2b8c978754f3824b6a0cb46cd44ca9c43692#commitcomment-14766875
I tested the code on my Marantz AVR. TrueHD works as expected.
> ActiveAEStream: Avoid memcpy but take care for byte access

- xbmc/cores/VideoPlayer/VideoPlayer.cpp
- xbmc/cores/VideoPlayer/VideoPlayer.h
As omxplayer can create and destroy the player (e.g. based on hardware codec support)
there is currently a thread safety issue.
Add a lock around player create/destroy to protect this.
> [videoplayer] Add lock for player creation

- project/cmake/modules/FindCpluff.cmake
- project/cmake/modules/FindD3DX11Effects.cmake
- xbmc/filesystem/CMakeLists.txt
- xbmc/filesystem/DAVDirectory.cpp
- xbmc/win32/PlatformDefs.h
@FernetMenta: Last set of changes for this year ;) Hope it's fine for you if they come in smaller chunks.
This time, there are 2 commits that touch header files in order to fix implicit include order dependencies.
Not sure if they should go to the main Kodi repository directly.
@wsnipex: For some of the dependencies we'll need to use mingw/msys (if I'm not mistaken).
Do you have an idea how to use ExternalProject_Add with mingw?
For example in https://github.com/FernetMenta/xbmc/blob/master/project/cmake/modules/FindLibDvd.cmake.
Happy new year!
Christian
> [cmake] More work on Windows support

- xbmc/guilib/FFmpegImage.cpp
While implementing it I forgot to check the exif orientation information. Luckily this is kept in ffmpeg's AVDictionary that we get after decoding the frame.
> FFmpegImage: Fix Orientation of image

- addons/library.xbmc.addon/libXBMC_addon.h
- lib/addons/library.xbmc.addon/libXBMC_addon.cpp
- xbmc/addons/AddonCallbacks.h
- xbmc/addons/AddonCallbacksAddon.cpp
- xbmc/addons/AddonCallbacksAddon.h
This is just the framework for replacing | added options to an URL - if this is OK I would finalize this in CCurl.
> Added addon callback to allow addons to set transfer options

- xbmc/addons/AddonCallbacksAddon.cpp
- xbmc/filesystem/CurlFile.cpp
- xbmc/filesystem/CurlFile.h
- xbmc/filesystem/File.cpp
- xbmc/filesystem/File.h
- xbmc/filesystem/IFile.h
This is the final implementation in CCurlFile.
The deprecated solution using | is still supported
> Implementation of AddTransferOption() in CCurlFile

- xbmc/addons/InputStream.cpp
- xbmc/cores/VideoPlayer/DVDInputStreams/DVDFactoryInputStream.cpp
Curl should be compiled with gzip option - is this assured?
mpd files could be large (5MB and more) and this option in combination with enabled gzip curl support speeds up starting time of videos significant.
> Load Inputstream addon only if extension matches / regexp for path comparision

- addons/library.xbmc.addon/libXBMC_addon.h
- lib/addons/library.xbmc.addon/libXBMC_addon.cpp
- project/cmake/installdata/addon-bindings.txt
- xbmc/addons/AddonCallbacks.h
- xbmc/addons/AddonCallbacksAddon.cpp
- xbmc/addons/AddonCallbacksAddon.h
- xbmc/addons/addon-bindings.mk
- xbmc/filesystem/CurlFile.cpp
- xbmc/filesystem/CurlFile.h
- xbmc/filesystem/File.cpp
- xbmc/filesystem/File.h
- xbmc/filesystem/IFile.h
- xbmc/filesystem/IFileTypes.h
- xbmc/interfaces/legacy/File.h
- xbmc/network/WebServer.cpp
- xbmc/network/httprequesthandler/HTTPFileHandler.cpp
This implementation enables addon developers to fill an CCurl struct using three callback functions
- CURLCreate: Creates an instance of CFile and initializes an CCURL member
- CURLAddOption lets the developer set CURL options  (options / credentials..)
- CURLOpen finally calles open on the underlying stream
Furthermore CURLINFO_SPEED_DOWNLOAD is implemented
Moving XFILE constants (READ_NO_CACHE...) to IFileTypes.h and adding this file to the addon-bindings enable developers to use these constants by including this file in the addon.
> Curloptions

- xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEFilter.cpp
As debugged two seconds ago. We should probably align everything on value 32 or 64, too. And perhaps also our memory adresses to 64.
> ActiveAEFilter: Properly tell our alignment - or ffmpeg will align on 32

- xbmc/windowing/egl/CMakeLists.txt
- xbmc/windowing/egl/VideoSyncPi.cpp
- xbmc/windowing/egl/VideoSyncPi.h
- xbmc/windowing/egl/WinSystemEGL.cpp
- xbmc/windowing/egl/WinSystemEGL.h
Previous version was just compiling but not actually plumbed in.
This seems to be active.
> fixup! RPi: Fixup move of videosync to windowing
